FROM node:18 AS build

WORKDIR /app
COPY package.json package-lock.json* /app/
RUN npm ci
COPY . /app
RUN npm run build

FROM nginx:alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
